# shellcheck shell=bash
export XDG_BIN_HOME="${XDG_BIN_HOME:=${HOME}/.local/bin}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:=${HOME}/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=${HOME}/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:=${HOME}/.local/share}"
export XDG_LIB_HOME="${XDG_LIB_HOME:=${HOME}/.local/lib}"

export PATH="${XDG_BIN_HOME}:${PATH}"

export IPYTHONDIR="${XDG_CONFIG_HOME}/ipython"
export LESSHISTFILE="${XDG_DATA_HOME}/less/history"
export PYTHONSTARTUP="${XDG_CONFIG_HOME}/python/startup.py"
export PYLINTHOME="${XDG_DATA_HOME}/pylint"
export PYLINTRC="${XDG_CONFIG_HOME}/pylint/pylintrc"
export YADM_DIR="${XDG_DATA_HOME}/yadm"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"
export ZINIT_HOME="${XDG_DATA_HOME}/zinit"

# Skip the unncessary Ubuntu global compinit
skip_global_compinit=1

