#!/bin/sh
# shellcheck disable=SC3045

while [ -z "$SKIP_INTERACTIVE_BOOTSTRAP" ]; do
    read -rp "Decrypt yadm secrets? " yn
    case $yn in
        [Yy]* ) yadm decrypt; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done

while [ -z "$SKIP_INTERACTIVE_BOOTSTRAP" ]; do
    read -rp "Tag this machine with the work class? " yn
    case $yn in
        [Yy]* ) yadm config --add local.class work; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

yadm alt

echo "Setup successful, restart zsh to apply settings!"
