TMPPREFIX=~/tmp/zsh-
mkdir -p ~/tmp

source ~/tools/zsh/zgen/zgen.zsh

# if the init scipt doesn't exist
if ! zgen saved; then

  # Initialize prezto
  zgen prezto
  zgen prezto git
  zgen prezto node
  zgen prezto autosuggestions
  zgen prezto completion
  zgen prezto utility
  zgen prezto prompt

  # Easier directory traversal
  zgen load Tarrasch/zsh-bd
  
  # Tips for defined aliases
  zgen load djui/alias-tips
  
  zgen load zsh-users/zsh-syntax-highlighting
  
  # Peco History search
  zgen load jimeh/zsh-peco-history
  
  # Better directory listings
  zgen load supercrabtree/k

  # Dircolors solarized
  zgen load joel-porquet/zsh-dircolors-solarized
  
  # generate the init script from plugins above
  zgen save
fi

# Change history to be shared
HISTFILE=~/.zhistory
HISTSIZE=SAVEHIST=5000
setopt incappendhistory
setopt sharehistory
setopt extendedhistory

# Change autosuggestions color
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE=fg=4

# ssh-agent via keychain
eval $(keychain --eval --agents ssh --timeout 120 -Q id_rsa)

case $HOSTNAME in
  (canopus.uberspace.de) eval $(keychain --eval --agents gpg --timeout 120 -Q 484E4C89);;
  (*) ;;
esac

# Export gpg-agent info from keychain
if [ -f ~/.gpg-agent-info ]
then
  source ~/.gpg-agent-info
  export $(cat ~/.gpg-agent-info)
fi

# bindkey
bindkey -e

# load aliases
source ~/tools/zsh/aliases.zsh

source ~/tools/zsh/bindkeys.zsh

# Init solarized dir colors
setupsolarized dircolors.ansi-dark
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

alias ls='ls --color=auto'

typeset -U path

path[1,0]=/package/host/localhost/ruby-2.2.0/bin
path[1,0]=~/.gem/ruby/2.2.0/bin
path[1,0]=/package/host/localhost/nodejs-5/bin

case $HOSTNAME in
  (canopus.uberspace.de) path[1,0]=/package/host/localhost/zsh/bin/;;
  (*) ;;
esac
