source ~/tools/zsh/zgen/zgen.zsh

# if the init scipt doesn't exist
if ! zgen saved; then

  # Load plugins
  zgen oh-my-zsh
  zgen oh-my-zsh plugins/composer
  zgen oh-my-zsh plugins/common-aliases
  zgen oh-my-zsh plugins/dirhistory
  zgen oh-my-zsh plugins/extract
  zgen oh-my-zsh plugins/gem
  zgen oh-my-zsh plugins/git
  zgen oh-my-zsh plugins/git-extras
  zgen oh-my-zsh plugins/mosh
  zgen oh-my-zsh plugins/npm
  zgen oh-my-zsh plugins/tmux
  zgen oh-my-zsh plugins/wd
  
  # Easier directory traversal
  zgen load Tarrasch/zsh-bd
  
  # Tips for defined aliases
  zgen load djui/alias-tips
  
  zgen load zsh-users/zsh-syntax-highlighting
  zgen load zsh-users/zsh-autosuggestions
  
  # Peco History search
  zgen load jimeh/zsh-peco-history
  
  # Better directory listings
  zgen load supercrabtree/k
  
  # Load Theme
  zgen oh-my-zsh themes/ys
  
  # Dircolors solarized
  zgen load joel-porquet/zsh-dircolors-solarized
  
  # Load additional completions
  zgen load zsh-users/zsh-completions src
  
  # generate the init script from plugins above
  zgen save
fi

# Change history to be shared
HISTFILE=~/.zhistory
HISTSIZE=SAVEHIST=5000
setopt incappendhistory
setopt sharehistory
setopt extendedhistory

# Change autosuggestions color
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE=fg=4

#ssh-agent via keychain
eval $(keychain --eval --agents ssh --timeout 120 -Q id_rsa)

case $HOSTNAME in
  (canopus.uberspace.de) keychain --eval --agents gpg --timeout 120 -Q 484E4C89;;
  (*) ;;
esac

# bindkey
bindkey -e
bindkey "\e[3~" delete-char
# # Home- und End-Keys.
bindkey '\e[1~' beginning-of-line
bindkey '\e[4~' end-of-line

typeset -U path

path[1,0]=/package/host/localhost/ruby-2.2.0/bin
path[1,0]=~/.gem/ruby/2.2.0/bin
path[1,0]=/package/host/localhost/nodejs-5/bin
